# Dependencies
markdown:         redcarpet
highlighter:      false

# Permalinks
permalink:        pretty

## deprecated from jekyll 3+
# relative_permalinks: true

# Setup
title:            '&#268;SDS Brusel'
tagline:          '&#268;eskoslovensk&aacute; Doprovodn&aacute; Skupina Brusel'
description:      'Midi soubory a nic vic.'
url:              
baseurl:          /

author:
  name:           'ulf gjerdingen'
  url:            https://ulfgj.github.io

# gems: [jekyll-paginate]
paginate:         5

# TODO
  # menu / navigation translation

# Custom vars
version:          0.0.1

github:
  repo:           
